import json

# JSON 데이터를 파싱합니다.
data = """
{
  "response": {
    "header": {
      "resultMsg": "NORMAL_CODE",
      "resultCode": "00"
    },
    "body": {
      "totalCount": "1374",
      "items": {
        "item": [
          {
            "subject": "도니가족발",
            "contents": "...",
            "boardCode": "200a01",
            "boardCodeNm": "1호선",
            "registerDate": "2018-06-15",
            "setValue": "10|7|6|5|10|7|6|5|11|11",
            "setValueNm": "음식점|경사로|이용가능시설|자동문|음식점|경사로|이용가능시설|자동문|입식테이블|입식테이블",
            "gubun": "도시철도 음식점",
            "imgUrl": null
          },
          {
            "subject": "장산수제왕돈까스",
            "contents": "...",
            "boardCode": "200a02",
            "boardCodeNm": "2호선",
            "registerDate": "2018-06-15",
            "setValue": "11|10|6|5|11|10|6|5",
            "setValueNm": "입식테이블|음식점|이용가능시설|자동문|입식테이블|음식점|이용가능시설|자동문",
            "gubun": "도시철도 음식점",
            "imgUrl": null
          }
          # ... 다른 항목들 ...
        ]
      },
      "pageNo": "1",
      "numOfRows": "10"
    }
  }
}
"""

# JSON 데이터를 파싱하여 파이썬 객체로 변환합니다.
parsed_data = json.loads(data)

# 휠체어 접근 가능 여부를 확인하는 함수
def is_wheelchair_accessible(item):
    # 휠체어 접근에 필수적인 요소들
    required_features = ["경사로", "이용가능시설", "자동문"]
    
    # setValueNm 필드를 가져옵니다.
    features = item.get("setValueNm", "")
    
    # 모든 필수 요소가 있는지 확인합니다.
    return all(feature in features for feature in required_features)

# 결과를 확인합니다.
for item in parsed_data["response"]["body"]["items"]["item"]:
    subject = item["subject"]
    accessible = is_wheelchair_accessible(item)
    print(f"{subject}는 휠체어 접근 {'가능' if accessible else '불가능'}합니다.")

